project_id = "tedkllggdmwhxtxwqrzk"

[functions.feed-get]
verify_jwt = false

[functions.scores-refresh-user]
verify_jwt = true

[functions.job-application-create]
verify_jwt = true

[functions.job-application-select]
verify_jwt = true

[functions.admin-kyc]
verify_jwt = true

[functions.public-signup]
verify_jwt = false
