// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || "https://tedkllggdmwhxtxwqrzk.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "sb_publishable_uZp6qQA4agB_MgDFmbuzUg_Blk4PzhB";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// NOTE: previously an invoke-wrapper routed function calls through a
// reverse proxy at /marketplace-api that only exists on one specific
// hosting setup; on every other deployment it silently broke functions
// (proposals, notifications, payments). Functions are now called
// directly at the Supabase URL — CORS is open on all edge functions.
